# Generated by Django 6.0.6 on 2026-06-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('work_experience', models.PositiveIntegerField()),
                ('room_number', models.CharField(max_length=50)),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
